DROP SCHEMA IF EXISTS reporting CASCADE;
CREATE SCHEMA reporting;
drop view if exists  reporting.flight;
create view reporting.flight as 
select *,
case
	when dep_delay_new > 0 then 1 
	else 0
end as is_delayed
from
	flight;
DROP VIEW IF EXISTS REPORTING.TOP_RELIABILITY_ROADS;
CREATE VIEW REPORTING.TOP_RELIABILITY_ROADS AS
	WITH CTE AS (
		SELECT F.YEAR :: VARCHAR, F.ORIGIN_AIRPORT_ID, AL_ORIG.DISPLAY_AIRPORT_NAME AS ORIG_AIRPORT_NAME, 
		F.DEST_AIRPORT_ID, AL_DEST.DISPLAY_AIRPORT_NAME AS DEST_AIRPORT_NAME, SUM(IS_DELAYED) AS SUM_DELAYED, COUNT(*) AS ALL_FLIGHTS
		FROM REPORTING.FLIGHT F
		LEFT JOIN AIRPORT_LIST AL_ORIG ON
		F.ORIGIN_AIRPORT_ID = AL_ORIG.ORIGIN_AIRPORT_ID
		INNER JOIN AIRPORT_LIST AL_DEST ON
		F.DEST_AIRPORT_ID = AL_DEST.ORIGIN_AIRPORT_ID
		GROUP BY 
		F.ORIGIN_AIRPORT_ID, F.YEAR, DEST_AIRPORT_NAME, DEST_AIRPORT_ID, AL_ORIG.DISPLAY_AIRPORT_NAME
	)
	SELECT *, CAST((SUM_DELAYED::FLOAT / ALL_FLIGHTS)  AS DECIMAL (5, 2)) AS RELIABILITY, DENSE_RANK () OVER (ORDER BY CAST((SUM_DELAYED::FLOAT / ALL_FLIGHTS)  AS DECIMAL (5, 2))DESC) AS nb
	FROM CTE
	WHERE ALL_FLIGHTS > 10000
	ORDER BY ALL_FLIGHTS DESC , YEAR ASC;
DROP VIEW IF EXISTS reporting.year_to_year_comparision;
CREATE VIEW reporting.year_to_year_comparision AS
	WITH CTE_2 AS (
		SELECT F.YEAR :: VARCHAR, f.month,  SUM(IS_DELAYED) AS SUM_DELAYED, COUNT(*) AS ALL_FLIGHTS
		FROM REPORTING.FLIGHT F
		LEFT JOIN AIRPORT_LIST AL_ORIG ON
		F.ORIGIN_AIRPORT_ID = AL_ORIG.ORIGIN_AIRPORT_ID
		INNER JOIN AIRPORT_LIST AL_DEST ON
		F.DEST_AIRPORT_ID = AL_DEST.ORIGIN_AIRPORT_ID
		GROUP BY 
		F.YEAR, F.month
	)
	SELECT year,  month,ALL_FLIGHTS, CAST((SUM_DELAYED::FLOAT / ALL_FLIGHTS)  AS DECIMAL (5, 2)) AS RELIABILITY   
	FROM CTE_2
	ORDER BY YEAR ASC, month asc;
DROP VIEW IF EXISTS reporting.DAY_to_day_comparison;
CREATE VIEW reporting.day_to_day_comparision AS
	WITH CTE_3 AS (
		SELECT F.YEAR :: VARCHAR, day_of_week , COUNT(*) AS ALL_FLIGHTS
		FROM REPORTING.FLIGHT F
		LEFT JOIN AIRPORT_LIST AL_ORIG ON
		F.ORIGIN_AIRPORT_ID = AL_ORIG.ORIGIN_AIRPORT_ID
		INNER JOIN AIRPORT_LIST AL_DEST ON
		F.DEST_AIRPORT_ID = AL_DEST.ORIGIN_AIRPORT_ID
		GROUP BY 
		F.YEAR, day_of_week
	)
	SELECT year,  day_of_week,ALL_FLIGHTS    
	FROM CTE_3
	ORDER BY YEAR ASC, day_of_week ASC; 
DROP VIEW IF EXISTS reporting.day_by_day_reliability;
CREATE VIEW reporting.day_by_day_reliability AS
	WITH CTE_4 AS (
		SELECT F.YEAR :: VARCHAR, f.month, day_of_week,  SUM(IS_DELAYED) AS SUM_DELAYED, COUNT(*) AS ALL_FLIGHTS
		FROM REPORTING.FLIGHT F
		LEFT JOIN AIRPORT_LIST AL_ORIG ON
		F.ORIGIN_AIRPORT_ID = AL_ORIG.ORIGIN_AIRPORT_ID
		INNER JOIN AIRPORT_LIST AL_DEST ON
		F.DEST_AIRPORT_ID = AL_DEST.ORIGIN_AIRPORT_ID
		GROUP BY 
		F.YEAR, F.MONTH, day_of_week
	)
	SELECT to_date( YEAR || '-' || MONTH || '-' || day_of_week,   'YYYY-MM-DD') ALL_FLIGHTS, CAST((SUM_DELAYED::FLOAT / ALL_FLIGHTS) * 100 AS DECIMAL (5, 2)) AS RELIABILITY   
	FROM CTE_4
	ORDER BY YEAR ASC, month asc
